# Generated by Django 4.1.13 on 2024-03-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('closeDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
